wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1719035376
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 17
      - 23
      - 37
      4: 3.10.14
      5: 0.17.2
      8:
      - 1
      - 3
      - 5
      10:
      - 3
      13: windows-amd64
