wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1719036937
    t:
      1:
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.10.14
      5: 0.17.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    framework: torch
learning_rate:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 16
